"""add produto_personalizado_id to itens_pedido

Revision ID: 2856ef324a21
Revises: 
Create Date: 2025-10-04 23:02:54.973748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2856ef324a21'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('carrinho', 'produto',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('carrinho', 'quantidade',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index('ix_carrinho_id', table_name='carrinho')
    op.alter_column('categorias_produto', 'nome',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index('ix_categorias_produto_id', table_name='categorias_produto')
    op.alter_column('clientes', 'nome',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('clientes', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('clientes_email_key', 'clientes', type_='unique')
    op.drop_index('ix_clientes_id', table_name='clientes')
    op.alter_column('cupons', 'codigo',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index('ix_cupons_id', table_name='cupons')
    op.drop_index('ix_entregas_id', table_name='entregas')
    op.alter_column('funcionarios', 'nome',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index('ix_funcionarios_id', table_name='funcionarios')
    op.alter_column('ingredientes', 'nome',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index('ix_ingredientes_id', table_name='ingredientes')
    op.add_column('itens_pedido', sa.Column('produto_personalizado_id', sa.Integer(), nullable=True))
    op.alter_column('itens_pedido', 'produto_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_itens_pedido_id'), 'itens_pedido', ['id'], unique=False)
    op.create_foreign_key(None, 'itens_pedido', 'pizza_personalizada', ['produto_personalizado_id'], ['id'])
    op.drop_index('ix_pagamentos_id', table_name='pagamentos')
    op.alter_column('pedidos', 'cliente_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('pedidos', 'descricao',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'Pizza padrão'::character varying"))
    op.alter_column('pedidos', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'cliente@teste.com'::character varying"))
    op.alter_column('pedidos', 'valor_total',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('pedidos', 'quantidade',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.drop_index('ix_pedidos_id', table_name='pedidos')
    op.drop_constraint('pedidos_cliente_id_fkey', 'pedidos', type_='foreignkey')
    op.create_foreign_key(None, 'pedidos', 'clientes', ['cliente_id'], ['id'])
    op.drop_index('ix_pizza_ingredientes_id', table_name='pizza_ingredientes')
    op.drop_index('ix_pizza_personalizada_id', table_name='pizza_personalizada')
    op.alter_column('produtos', 'nome',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('produtos', 'preco',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_index('ix_produtos_id', table_name='produtos')
    op.drop_index('ix_usuarios_id', table_name='usuarios')
    op.drop_column('usuarios', 'senha')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('senha', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_usuarios_id', 'usuarios', ['id'], unique=False)
    op.create_index('ix_produtos_id', 'produtos', ['id'], unique=False)
    op.alter_column('produtos', 'preco',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('produtos', 'nome',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index('ix_pizza_personalizada_id', 'pizza_personalizada', ['id'], unique=False)
    op.create_index('ix_pizza_ingredientes_id', 'pizza_ingredientes', ['id'], unique=False)
    op.drop_constraint(None, 'pedidos', type_='foreignkey')
    op.create_foreign_key('pedidos_cliente_id_fkey', 'pedidos', 'clientes', ['cliente_id'], ['id'])
    op.create_index('ix_pedidos_id', 'pedidos', ['id'], unique=False)
    op.alter_column('pedidos', 'quantidade',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('pedidos', 'valor_total',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('pedidos', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'cliente@teste.com'::character varying"))
    op.alter_column('pedidos', 'descricao',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'Pizza padrão'::character varying"))
    op.alter_column('pedidos', 'cliente_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index('ix_pagamentos_id', 'pagamentos', ['id'], unique=False)
    op.drop_constraint(None, 'itens_pedido', type_='foreignkey')
    op.drop_index(op.f('ix_itens_pedido_id'), table_name='itens_pedido')
    op.alter_column('itens_pedido', 'produto_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('itens_pedido', 'produto_personalizado_id')
    op.create_index('ix_ingredientes_id', 'ingredientes', ['id'], unique=False)
    op.alter_column('ingredientes', 'nome',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index('ix_funcionarios_id', 'funcionarios', ['id'], unique=False)
    op.alter_column('funcionarios', 'nome',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index('ix_entregas_id', 'entregas', ['id'], unique=False)
    op.create_index('ix_cupons_id', 'cupons', ['id'], unique=False)
    op.alter_column('cupons', 'codigo',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index('ix_clientes_id', 'clientes', ['id'], unique=False)
    op.create_unique_constraint('clientes_email_key', 'clientes', ['email'])
    op.alter_column('clientes', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('clientes', 'nome',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index('ix_categorias_produto_id', 'categorias_produto', ['id'], unique=False)
    op.alter_column('categorias_produto', 'nome',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index('ix_carrinho_id', 'carrinho', ['id'], unique=False)
    op.alter_column('carrinho', 'quantidade',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('carrinho', 'produto',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
