"""setup_inicial

Revision ID: 6c6d401d252e
Revises: 760dab23b665
Create Date: 2025-10-18 19:06:06.812390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c6d401d252e'
down_revision = '760dab23b665'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_carrinho_id'), 'carrinho', ['id'], unique=False)
    op.drop_constraint('clientes_usuario_id_fkey', 'clientes', type_='foreignkey')
    op.create_foreign_key(None, 'clientes', 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('cupons_codigo_key', 'cupons', type_='unique')
    op.create_index(op.f('ix_cupons_codigo'), 'cupons', ['codigo'], unique=True)
    op.create_index(op.f('ix_cupons_id'), 'cupons', ['id'], unique=False)
    op.create_index(op.f('ix_entregas_id'), 'entregas', ['id'], unique=False)
    op.create_index(op.f('ix_entregas_status'), 'entregas', ['status'], unique=False)
    op.create_unique_constraint(None, 'entregas', ['pedido_id'])
    op.drop_constraint('entregas_pedido_id_fkey', 'entregas', type_='foreignkey')
    op.create_foreign_key(None, 'entregas', 'pedidos', ['pedido_id'], ['id'], ondelete='CASCADE')
    op.add_column('funcionarios', sa.Column('nome', sa.String(), nullable=False))
    op.add_column('funcionarios', sa.Column('email', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'funcionarios', ['email'])
    op.drop_constraint('funcionarios_usuario_id_fkey', 'funcionarios', type_='foreignkey')
    op.create_foreign_key(None, 'funcionarios', 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE')
    op.add_column('ingredientes', sa.Column('preco', sa.Float(), nullable=True))
    op.add_column('ingredientes', sa.Column('disponivel', sa.Boolean(), nullable=True))
    op.drop_constraint('ingredientes_nome_key', 'ingredientes', type_='unique')
    op.create_index(op.f('ix_ingredientes_id'), 'ingredientes', ['id'], unique=False)
    op.create_index(op.f('ix_ingredientes_nome'), 'ingredientes', ['nome'], unique=True)
    op.create_index(op.f('ix_itens_pedido_id'), 'itens_pedido', ['id'], unique=False)
    op.drop_constraint('itens_pedido_pedido_id_fkey', 'itens_pedido', type_='foreignkey')
    op.create_foreign_key(None, 'itens_pedido', 'pedidos', ['pedido_id'], ['id'], ondelete='CASCADE')
    op.add_column('pagamentos', sa.Column('status', sa.String(), nullable=True))
    op.alter_column('pagamentos', 'forma_pagamento',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('pagamentos', 'valor',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.create_index(op.f('ix_pagamentos_id'), 'pagamentos', ['id'], unique=False)
    op.create_unique_constraint(None, 'pagamentos', ['pedido_id'])
    op.drop_constraint('pagamentos_pedido_id_fkey', 'pagamentos', type_='foreignkey')
    op.create_foreign_key(None, 'pagamentos', 'pedidos', ['pedido_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_pedidos_data_pedido'), 'pedidos', ['data_pedido'], unique=False)
    op.create_index(op.f('ix_pedidos_id'), 'pedidos', ['id'], unique=False)
    op.create_index(op.f('ix_pedidos_status'), 'pedidos', ['status'], unique=False)
    op.add_column('pizza_ingredientes', sa.Column('quantidade', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_pizza_ingredientes_id'), 'pizza_ingredientes', ['id'], unique=False)
    op.drop_constraint('pizza_ingredientes_pizza_personalizada_id_fkey', 'pizza_ingredientes', type_='foreignkey')
    op.create_foreign_key(None, 'pizza_ingredientes', 'pizza_personalizada', ['pizza_personalizada_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_pizza_personalizada_id'), 'pizza_personalizada', ['id'], unique=False)
    op.add_column('produtos', sa.Column('ativo', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_produtos_id'), 'produtos', ['id'], unique=False)
    op.create_index(op.f('ix_produtos_nome'), 'produtos', ['nome'], unique=False)
    op.drop_constraint('usuarios_email_key', 'usuarios', type_='unique')
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.create_unique_constraint('usuarios_email_key', 'usuarios', ['email'])
    op.drop_index(op.f('ix_produtos_nome'), table_name='produtos')
    op.drop_index(op.f('ix_produtos_id'), table_name='produtos')
    op.drop_column('produtos', 'ativo')
    op.drop_index(op.f('ix_pizza_personalizada_id'), table_name='pizza_personalizada')
    op.drop_constraint(None, 'pizza_ingredientes', type_='foreignkey')
    op.create_foreign_key('pizza_ingredientes_pizza_personalizada_id_fkey', 'pizza_ingredientes', 'pizza_personalizada', ['pizza_personalizada_id'], ['id'])
    op.drop_index(op.f('ix_pizza_ingredientes_id'), table_name='pizza_ingredientes')
    op.drop_column('pizza_ingredientes', 'quantidade')
    op.drop_index(op.f('ix_pedidos_status'), table_name='pedidos')
    op.drop_index(op.f('ix_pedidos_id'), table_name='pedidos')
    op.drop_index(op.f('ix_pedidos_data_pedido'), table_name='pedidos')
    op.drop_constraint(None, 'pagamentos', type_='foreignkey')
    op.create_foreign_key('pagamentos_pedido_id_fkey', 'pagamentos', 'pedidos', ['pedido_id'], ['id'])
    op.drop_constraint(None, 'pagamentos', type_='unique')
    op.drop_index(op.f('ix_pagamentos_id'), table_name='pagamentos')
    op.alter_column('pagamentos', 'valor',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('pagamentos', 'forma_pagamento',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('pagamentos', 'status')
    op.drop_constraint(None, 'itens_pedido', type_='foreignkey')
    op.create_foreign_key('itens_pedido_pedido_id_fkey', 'itens_pedido', 'pedidos', ['pedido_id'], ['id'])
    op.drop_index(op.f('ix_itens_pedido_id'), table_name='itens_pedido')
    op.drop_index(op.f('ix_ingredientes_nome'), table_name='ingredientes')
    op.drop_index(op.f('ix_ingredientes_id'), table_name='ingredientes')
    op.create_unique_constraint('ingredientes_nome_key', 'ingredientes', ['nome'])
    op.drop_column('ingredientes', 'disponivel')
    op.drop_column('ingredientes', 'preco')
    op.drop_constraint(None, 'funcionarios', type_='foreignkey')
    op.create_foreign_key('funcionarios_usuario_id_fkey', 'funcionarios', 'usuarios', ['usuario_id'], ['id'])
    op.drop_constraint(None, 'funcionarios', type_='unique')
    op.drop_column('funcionarios', 'email')
    op.drop_column('funcionarios', 'nome')
    op.drop_constraint(None, 'entregas', type_='foreignkey')
    op.create_foreign_key('entregas_pedido_id_fkey', 'entregas', 'pedidos', ['pedido_id'], ['id'])
    op.drop_constraint(None, 'entregas', type_='unique')
    op.drop_index(op.f('ix_entregas_status'), table_name='entregas')
    op.drop_index(op.f('ix_entregas_id'), table_name='entregas')
    op.drop_index(op.f('ix_cupons_id'), table_name='cupons')
    op.drop_index(op.f('ix_cupons_codigo'), table_name='cupons')
    op.create_unique_constraint('cupons_codigo_key', 'cupons', ['codigo'])
    op.drop_constraint(None, 'clientes', type_='foreignkey')
    op.create_foreign_key('clientes_usuario_id_fkey', 'clientes', 'usuarios', ['usuario_id'], ['id'])
    op.drop_index(op.f('ix_carrinho_id'), table_name='carrinho')
    # ### end Alembic commands ###
