"""Unificar IDs de clientes e funcionarios

Revision ID: 760dab23b665
Revises: realign_0001
Create Date: 2025-10-16 16:14:43.735895

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '760dab23b665'
down_revision = 'realign_0001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tamanhos_pizza')
    op.drop_table('avaliacoes')
    op.alter_column('carrinho', 'quantidade',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_carrinho_id'), 'carrinho', ['id'], unique=False)
    op.create_foreign_key(None, 'carrinho', 'produtos', ['produto_id'], ['id'])
    op.create_foreign_key(None, 'carrinho', 'pizza_personalizada', ['produto_personalizado_id'], ['id'])
    op.drop_column('carrinho', 'produto')
    op.alter_column('categorias_produto', 'nome',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_categorias_produto_id'), 'categorias_produto', ['id'], unique=False)
    op.create_unique_constraint(None, 'categorias_produto', ['nome'])
    op.alter_column('clientes', 'telefone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('clientes', 'endereco',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('clientes', 'nome')
    op.drop_column('clientes', 'email')
    op.alter_column('cupons', 'codigo',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('cupons', 'percentual_desconto',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.create_index(op.f('ix_cupons_id'), 'cupons', ['id'], unique=False)
    op.create_index(op.f('ix_entregas_id'), 'entregas', ['id'], unique=False)
    op.drop_column('entregas', 'endereco')
    op.alter_column('funcionarios', 'nome',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('ingredientes', 'nome',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_ingredientes_id'), 'ingredientes', ['id'], unique=False)
    op.create_unique_constraint(None, 'ingredientes', ['nome'])
    op.drop_column('ingredientes', 'tipo')
    op.drop_column('ingredientes', 'descricao')
    op.drop_column('ingredientes', 'preco')
    op.alter_column('itens_pedido', 'pedido_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_pagamentos_id'), 'pagamentos', ['id'], unique=False)
    op.alter_column('pedidos', 'quantidade',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('pedidos', 'valor_total',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.create_index(op.f('ix_pedidos_id'), 'pedidos', ['id'], unique=False)
    op.create_index(op.f('ix_pizza_ingredientes_id'), 'pizza_ingredientes', ['id'], unique=False)
    op.drop_constraint('pizza_ingredientes_pizza_id_fkey', 'pizza_ingredientes', type_='foreignkey')
    op.drop_column('pizza_ingredientes', 'pizza_id')
    op.drop_column('pizza_ingredientes', 'quantidade')
    op.alter_column('pizza_personalizada', 'nome',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('pizza_personalizada', 'preco_base',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.create_index(op.f('ix_pizza_personalizada_id'), 'pizza_personalizada', ['id'], unique=False)
    op.drop_column('pizza_personalizada', 'tamanho')
    op.drop_column('pizza_personalizada', 'borda')
    op.alter_column('produtos', 'nome',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('produtos', 'preco',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.create_index(op.f('ix_produtos_id'), 'produtos', ['id'], unique=False)
    op.drop_column('produtos', 'tipo')
    op.alter_column('usuarios', 'tipo_usuario',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'cliente'::character varying"))
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.alter_column('usuarios', 'tipo_usuario',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'cliente'::character varying"))
    op.add_column('produtos', sa.Column('tipo', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_produtos_id'), table_name='produtos')
    op.alter_column('produtos', 'preco',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('produtos', 'nome',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('pizza_personalizada', sa.Column('borda', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('pizza_personalizada', sa.Column('tamanho', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_pizza_personalizada_id'), table_name='pizza_personalizada')
    op.alter_column('pizza_personalizada', 'preco_base',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('pizza_personalizada', 'nome',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('pizza_ingredientes', sa.Column('quantidade', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pizza_ingredientes', sa.Column('pizza_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('pizza_ingredientes_pizza_id_fkey', 'pizza_ingredientes', 'produtos', ['pizza_id'], ['id'])
    op.drop_index(op.f('ix_pizza_ingredientes_id'), table_name='pizza_ingredientes')
    op.drop_index(op.f('ix_pedidos_id'), table_name='pedidos')
    op.alter_column('pedidos', 'valor_total',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('pedidos', 'quantidade',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.drop_index(op.f('ix_pagamentos_id'), table_name='pagamentos')
    op.alter_column('itens_pedido', 'pedido_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('ingredientes', sa.Column('preco', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('ingredientes', sa.Column('descricao', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('ingredientes', sa.Column('tipo', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'ingredientes', type_='unique')
    op.drop_index(op.f('ix_ingredientes_id'), table_name='ingredientes')
    op.alter_column('ingredientes', 'nome',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('funcionarios', 'nome',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('entregas', sa.Column('endereco', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_entregas_id'), table_name='entregas')
    op.drop_index(op.f('ix_cupons_id'), table_name='cupons')
    op.alter_column('cupons', 'percentual_desconto',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('cupons', 'codigo',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('clientes', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('clientes', sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('clientes', 'endereco',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('clientes', 'telefone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'categorias_produto', type_='unique')
    op.drop_index(op.f('ix_categorias_produto_id'), table_name='categorias_produto')
    op.alter_column('categorias_produto', 'nome',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('carrinho', sa.Column('produto', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'carrinho', type_='foreignkey')
    op.drop_constraint(None, 'carrinho', type_='foreignkey')
    op.drop_index(op.f('ix_carrinho_id'), table_name='carrinho')
    op.alter_column('carrinho', 'quantidade',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table('avaliacoes',
    sa.Column('cliente_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pedido_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comentario', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('data_avaliacao', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('nota', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.usuario_id'], name='avaliacoes_cliente_id_fkey'),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], name='avaliacoes_pedido_id_fkey'),
    sa.PrimaryKeyConstraint('cliente_id', 'pedido_id', name='avaliacoes_pkey')
    )
    op.create_table('tamanhos_pizza',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('descricao', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('preco', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('produto_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], name='fk_tamanho_produto', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='tamanhos_pizza_pkey')
    )
    # ### end Alembic commands ###
