"""add avaliacao model

Revision ID: e36443ecee4d
Revises: add_new_features_001
Create Date: 2025-10-25 12:41:05.296616

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e36443ecee4d'
down_revision = 'add_new_features_001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avaliacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('autor', sa.String(), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('nota', sa.Integer(), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('avaliacoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_avaliacoes_id'), ['id'], unique=False)

    with op.batch_alter_table('carrinho', schema=None) as batch_op:
        batch_op.drop_constraint('carrinho_cliente_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'clientes', ['cliente_id'], ['id'])

    with op.batch_alter_table('categorias_produto', schema=None) as batch_op:
        batch_op.alter_column('descricao',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.alter_column('endereco',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.drop_index('ix_clientes_usuario_id')

    with op.batch_alter_table('cupons', schema=None) as batch_op:
        batch_op.alter_column('percentual_desconto',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('ativo',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)

    with op.batch_alter_table('entregas', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=True)
        batch_op.drop_constraint('entregas_funcionario_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'funcionarios', ['funcionario_id'], ['id'])

    with op.batch_alter_table('funcionarios', schema=None) as batch_op:
        batch_op.drop_index('ix_funcionarios_usuario_id')

    with op.batch_alter_table('ingredientes', schema=None) as batch_op:
        batch_op.alter_column('preco',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)

    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.alter_column('quantidade',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('data_pedido',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=True)
        batch_op.drop_constraint('pedidos_cliente_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'clientes', ['cliente_id'], ['id'])

    with op.batch_alter_table('pizza_ingredientes', schema=None) as batch_op:
        batch_op.alter_column('quantidade',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('pizza_personalizada', schema=None) as batch_op:
        batch_op.drop_constraint('pizza_personalizada_cliente_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'clientes', ['cliente_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pizza_personalizada', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('pizza_personalizada_cliente_id_fkey', 'clientes', ['cliente_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('pizza_ingredientes', schema=None) as batch_op:
        batch_op.alter_column('quantidade',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('pedidos_cliente_id_fkey', 'clientes', ['cliente_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'pendente'::character varying"),
               existing_nullable=True)
        batch_op.alter_column('data_pedido',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
        batch_op.alter_column('quantidade',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=False)

    with op.batch_alter_table('ingredientes', schema=None) as batch_op:
        batch_op.alter_column('preco',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)

    with op.batch_alter_table('funcionarios', schema=None) as batch_op:
        batch_op.create_index('ix_funcionarios_usuario_id', ['usuario_id'], unique=False)

    with op.batch_alter_table('entregas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('entregas_funcionario_id_fkey', 'funcionarios', ['funcionario_id'], ['id'], ondelete='SET NULL')
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'pendente'::character varying"),
               existing_nullable=True)

    with op.batch_alter_table('cupons', schema=None) as batch_op:
        batch_op.alter_column('ativo',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
        batch_op.alter_column('percentual_desconto',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0.0'),
               existing_nullable=False)

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.create_index('ix_clientes_usuario_id', ['usuario_id'], unique=False)
        batch_op.alter_column('endereco',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('categorias_produto', schema=None) as batch_op:
        batch_op.alter_column('descricao',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    with op.batch_alter_table('carrinho', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('carrinho_cliente_id_fkey', 'clientes', ['cliente_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('avaliacoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_avaliacoes_id'))

    op.drop_table('avaliacoes')
    # ### end Alembic commands ###
